### ISSUE TITLE
Client-side error "cannot read undefined in morphChildren"

### ISSUE THREAD

**Issue by NicolasZanotti** [marko-js-samples/marko-browserify#1]
Hi,

I checked out this sample from the repo and was able to build without any warnings. On the client-side, however, I get the following error message upon execution.

<img width="652" alt="screen shot 2018-01-02 at 15 18 56" src="https://user-images.githubusercontent.com/837001/34486499-83d26946-efd0-11e7-84ae-62a0569fae80.png">

"Uncaught TypeError: Cannot read property 's0-5' of undefined at morphChildren (bundle.js:3013)"

My best bet is that something went out of sync with a newer Browserify version. I also checked your Webpack example–that works as expected.

Love the product!
Nick

**Comment by austinkelleher** [comment]
Hey, @NicolasZanotti. We are aware of this issue. This is actually an issue with [markoify](https://github.com/marko-js/markoify). It never got updated to support Marko v4. I'm not sure how soon we will get around to fixing this issue. I'd recommend using Webpack or Lasso for now if you can.

**Comment by austinkelleher** [comment]
@NicolasZanotti Opened https://github.com/marko-js/markoify/issues/11 to track this issue. Going to close out this issue.

**Comment by NicolasZanotti** [comment]
Got it, thank you @austinkelleher
